services:
  - name: twitter-to-telegram-bot
    type: worker
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TWITTER_USERNAME
        sync: false
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
